### PR TITLE
Add test spec ARN input

### PR DESCRIPTION
**Pull request by elashpear**
Closes https://github.com/peartherapeutics/bitrise-aws-device-farm-runner/issues/46

### CODE REVIEW

**Comment by saiyenumula** [comment]
Please someone can approve this PR @fadookie

**Comment by fadookie** [comment]
Sorry I have not had time to test it yet. I am planning on moving these repos over to the bitrise community organization soon so others can help maintain them as I don't even use them anymore

**Comment by vj-raghavan** [comment]
Hi @fadookie, Can we help you with testing this ? Adding test spec to the list would help us in the work we are doing straight away. Please let me know if there is anything we can do to help ?

**Comment by elashpear** [comment]
@vj-raghavan to simplify testing I can merge this to a non-master branch so you can point directly at it from your bitrise.yml and test to see if it works.

**Comment by elashpear** [comment]
@vj-raghavan I've merged these changes to the [ginmon-master](https://github.com/peartherapeutics/bitrise-aws-device-farm-runner/tree/ginmon-master) branch. You can point your `bitrise.yml` to [use this branch directly](https://devcenter.bitrise.io/bitrise-cli/steps/#special-step-sources) to verify that these changes do what's needed - I was not sure how to create a test case for this functionality.

We no longer use this step at my work so I am going to try to get it moved to the bitrise community org so it can be maintained there. If you're interested in being a new maintainer we could use one or more, I don't have time to do it anymore.

**Comment by elashpear** [comment]
Created a new PR to track movement of this code to master branch after testing is complete:
https://github.com/peartherapeutics/bitrise-aws-device-farm-runner/pull/52

**Comment by vj-raghavan** [comment]
@elashpear I have been using the code in our pipeline and can confirm that this works as intended. I was thinking there might be something else that we need to be doing. But if its getting it run locally and verify that the changes work as intended it does.

Please merge it in.

**Pull request merged**
