### PR TITLE
Add test spec ARN input

### PR DESCRIPTION
**Pull request by elashpear**
Clone of https://github.com/peartherapeutics/bitrise-aws-device-farm-runner/pull/51

Closes https://github.com/peartherapeutics/bitrise-aws-device-farm-runner/issues/46

[Need help testing!](https://github.com/peartherapeutics/bitrise-aws-device-farm-runner/pull/51#issuecomment-589411321)

### CODE REVIEW

**Comment by fadookie** [comment]
@vj-raghavan awesome, thank you! I will merge this to master but may not have time to cut a release until later. Are you interested in taking over as a maintainer of this step?

**Comment by vj-raghavan** [comment]
@fadookie I am okay to take over as a maintainer.

**Comment by elashpear** [comment]
@vj-raghavan great, thank you! I think what I am going to do is ask for this one and the file upload step to be moved to the official steplib and we can both be given write access - this will be easier going forward to have multiple maintainers.

I will cut one final release to make sure that's all still working.

**Comment by elashpear** [comment]
Release PR is up to steplib: https://github.com/bitrise-io/bitrise-steplib/pull/2412

**Comment by elashpear** [comment]
@vj-raghavan I have opened a support ticket to get this and the file-deploy step moved to bitrise-steplib organization and have you added as a mainainter.

**Pull request merged**
